// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using RestBar.Models;

#nullable disable

namespace RestBar.Migrations
{
    [DbContext(typeof(RestBarContext))]
    [Migration("20260731200000_RbUltimateMfaAndOrderNumberIndex")]
    partial class RbUltimateMfaAndOrderNumberIndex
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder) { }
    }
}
