// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using RestBar.Models;

#nullable disable

namespace RestBar.Migrations
{
    [DbContext(typeof(RestBarContext))]
    [Migration("20260731050000_BusinessRulesEnterprise")]
    partial class BusinessRulesEnterprise
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // SQL-only migration; model snapshot remains at SyncPendingModelChanges / ModelSnapshot.
        }
    }
}
