// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using RestBar.Models;

#nullable disable

namespace RestBar.Migrations
{
    [DbContext(typeof(RestBarContext))]
    [Migration("20260731120000_Rb1002PerformanceIndexes")]
    partial class Rb1002PerformanceIndexes
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
            // SQL-only performance indexes; snapshot unchanged intentionally.
        }
    }
}
